### ISSUE TITLE
Rotational Axis A,B or C

### ISSUE THREAD

**Issue by FAB619** [grblHAL/core#333]
Hi, I am working with custom made CNC 2 linear axis (X, Y) and 1 rotaional axis (A/B), I am running now the machine with Atmega2560 board and marlin firmware.  And now I am trying to install a teensy 4.1 board for high speed controlling and to be able to reach a higher speed for mass production. 
I tried to install marlin on the teensy but it didn't work or connect via USB maybe there is some libraries or modules missing, and I found grblHAL that worked directly with teensy and USB. 
I  am asking on how to configure a rotational axis in grblHAL, is it possible to configure the stepper stepping with step/deg (not step/mm)? 
Can I control the rotational axis (B axis) seperatly without stoping the Y axis? cause I read in another issue that when grbl controls a rotational axis the Y axis will stop working, it can not work together, Is there any solution for this ? 

Thank you.

**Comment by karoria** [comment]
1. Teensy4.1 will support up to 5 axis with grblHAL. Each axis will work individually.
2. To make a rotary axis unitless, you may configure $376 parameter. 0=steps/mm, 1=A axis unitless, 2=B axis unitless, 3=Both A and B axis unitless. For simplicity, you may consider it as step/deg.
3. Further, to make rotary axis A and B for infinity (no soft limit), you have to set $133 and $134 both parameter to 0 (zero).
4. Y axis and B axis are separate axis. You can control both individually. Some people use Y axis drive to control B axis motor to save for the hardware (to start a rotary axis job, they simply disconnect Y motor cable and connect B axis motor cable to the same drive because in that case, they don't need to use Y axis), that might be the reason for your confusion.
