### ISSUE TITLE
Just a question: I don't quite understand why Terje Io doesn't implement automatic tool changing based on upper computer processing?

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#343]
You have your own ioSender

**Comment by hanke-cnc** [comment]
Confusing

**Comment by terjeio** [comment]
Because I want it implemented on the controller for tight integration, which is now possible with [gcode macros stored on a SD card](https://github.com/grblHAL/core/discussions/309#discussioncomment-6099575) (or in flash if littlefs is available for the driver). This also does not restrict ATC functionality to ioSender, IMO it is better to let users choose which sender they want to use.
Oh, I and do not have to write generic ATC support for ioSender that would be hard to debug and maintain...
