### ISSUE TITLE
grblHAL porting to arduino nano every 

### ISSUE THREAD

**Issue by bluciano212** [grblHAL/core#387]
Hi , I wish to porting grblHAL to arduino nano every 
is it feasible ?how can I procede?
[Nano-Every_processor-48-pin-Data-Sheet-megaAVR-0-series-DS40002016B.pdf](https://github.com/grblHAL/core/files/13182780/Nano-Every_processor-48-pin-Data-Sheet-megaAVR-0-series-DS40002016B.pdf)

**Comment by terjeio** [comment]
No it is not feasible mostly due to grblHALs extensive use of function pointers which is not well suited for 8-bit processors. And 48K of flash is far from enough to  accomodate grblHAL.
If you want to port to another Arduino board he Uno R4 is a better choice, but even that is on the lower end of the other supported processors when it comes to performance.

If you are after the Nano form factor [Arduino Nano RP2040 Connect](https://store.arduino.cc/collections/boards-modules/products/arduino-nano-rp2040-connect) is a better choice?
