### ISSUE TITLE
Manual Tool Change 

### ISSUE THREAD

**Issue by SpikZASA** [grblHAL/core#601]
Hi terjeio

Would it be possible to make m6t0 (tool 0) to be like the probe tool that after you've probed your work piece with it, it will automatically goto the Tsetter location(G59.3) and probe down to set the TLR? that way at the first m6 in the gcode( usually M6t1) it will already have TLR and just have to fit first tool then it can goto Tsetter and get new TLO? i think this will be great and faster flow

**Comment by Dietz0r** [comment]
Hey,
if you just touch off your probe before setting the WCS it functions exactly like you want it to.
What kind of Toolnumber you give to the Probe doesnt really matter but usually we go for T99 because that's what some comercial controls and the probe protection plugin uses.

So the workflow is:
Install Probe -> M6T99 -> Set WCS -> load code and cycle start to toolchange to the first tool used in the code
